#ifndef FORTH_H_
#define FORTH_H_

#define CR      "CR"
#define DEPTH   "DEPTH"
#define DIV     "/"
#define DROP    "DROP"
#define DUP     "DUP"
#define EMIT    "EMIT"
#define EQ      "="
#define EXIT    "EXIT"
#define FETCH   "@"
#define GT      ">"
#define LT      "<"
#define MIN     "-"
#define MUL     "*"
#define NEG     "0<"
#define NOT     "NOT"
#define OVER    "OVER"
#define PICK    "PICK"
#define PLUS    "+"
#define POS     "0>"
#define PRINT   "."
#define RFETCH  "R@"
#define RFROM   "R>"
#define ROLL    "ROLL"
#define ROT     "ROT"
#define SPACE   "SPACE"
#define SPACES  "SPACES"
#define STORE   "!"
#define SWAP    "SWAP"
#define TOR     ">R"
#define ZERO    "0="

#endif

